config/routes.rb
Rails.application.routes.draw do

  resources :countries
  resources :cities
  root to: 'countries#index'

end

app/models/city.rb
class City < ActiveRecord::Base
  belongs_to :country
end

app/models/country.rb
class Country < ActiveRecord::Base
  has_many :cities, dependent: :destroy

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController

def index
  @cities = City.all
end

def show
  @city = City.find(params[:id])
end

def new
  @city = City.new
end

def create
  City.create(city_params)   #see the city_params from the private method below
  redirect_to(cities_path)
end

def destroy
  city = City.find(params[:id])  #doesn't need @ since it is not exposed - only being deleted
  city.destroy
  redirect_to(cities_path)
end

def edit
    @city = City.find(params[:id])

end

def update
  city = City.find(params[:id]) #again - the data does not need to be exposed - no @
  city.update(city_params) #from the private method below - whitelist check
  redirect_to(cities_path)
end  

private
def city_params
  # allows these params to be accessed by the methods above
  params.require(:city).permit(:name, :population, :country_id)
end

end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController

def index
  @countries = Country.all
  #@countries.sort!{ |a,b| a.name.downcase <=> b.name.downcase }
  #@country = Country.find(params[:id])
end

def show
  @country = Country.find(params[:id])
end

def new
  @country = Country.new
end

def create
  Country.create(country_params)   #see the team_params from the private method below
  redirect_to(countries_path)
end

def destroy
  country = Country.find(params[:id])  #doesn't need @ since it is not exposed - only being deleted
  country.destroy
  redirect_to(countries_path)
end

def edit
    @country = Country.find(params[:id])

end

def update
  country = Country.find(params[:id]) #again - the data does not need to be exposed - no @
  country.update(country_params) #from the private method below - whitelist check
  redirect_to(countries_path)
end  

private
def country_params
  # allows these params to be accessed by the methods above
  params.require(:country).permit(:name, :flag_image, :size, :gdp, :population, :language, :currency, :literacy_rate, :governing_party)
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cities/edit.html.erb
<div class='container'>
<div class='holder'>


<%= form_for @country do |f| %>
  <%= f.label :name, 'Country name:' %>
  <%= f.text_field :name %>
  <br>
  <br>
  <%= f.label :flag_image, 'Flag image URL:' %>
  <%= f.text_field :flag_image %>
  <br>
  <br>
  <%= f.label :size, 'Size in square miles' %>
  <%= f.number_field :size %>
  <br>
  <br>
  <%= f.label :gdp, 'GDP in billions (US Dollars):' %>
  <%= f.number_field :gdp %>
  <br>
  <br>
  <%= f.label :population, 'Population:' %>
  <%= f.number_field :population %>
  <br>
  <br>
  <%= f.label :language, 'Languages:' %>
  <%= f.text_field :language %>
  <br>
  <br>
  <%= f.label :currency, 'Currency:' %>
  <%= f.text_field :currency %>
  <br>
  <br>
  <%= f.label :literacy_rate, 'Literacy Rate (%):' %>
  <%= f.number_field :literacy_rate, in: 1.0..100.0, step: 1.0 %>
  <br>
  <br>
  <%= f.label :governing_party, 'Governing Party:' %>
  <%= f.text_field :governing_party %>
  <br>
  <br>
  <%= f.submit 'Update Country Details!!' %>
<% end %>

</div>
</div>

app/views/cities/index.html.erb
<div class='container'>
  <div class='holder'>
    <% @cities.sort.each do |city| %>
    
    <%= link_to(city.name, city_path(city)) %>
    <%#= button_to('Delete Country', country_path(country), method: :delete, data:{confirm: "Delete country? Are you sure?"}) %>
    <%#= link_to("Edit Country", edit_country_path(country)) %>
    <br>
    <% end %>
  </div>
</div>

app/views/cities/new.html.erb
<div class='container'>
<div class='holder'>


<%= form_for @country do |f| %>
  <%= f.label :name, 'Country name:' %>
  <%= f.text_field :name %>
  <br>
  <br>
  <%= f.label :flag_image, 'Flag image URL:' %>
  <%= f.text_field :flag_image %>
  <br>
  <br>
  <%= f.label :size, 'Size in square miles' %>
  <%= f.number_field :size %>
  <br>
  <br>
  <%= f.label :gdp, 'GDP in billions (US Dollars):' %>
  <%= f.number_field :gdp %>
  <br>
  <br>
  <%= f.label :population, 'Population:' %>
  <%= f.number_field :population %>
  <br>
  <br>
  <%= f.label :language, 'Languages:' %>
  <%= f.text_field :language %>
  <br>
  <br>
  <%= f.label :currency, 'Currency:' %>
  <%= f.text_field :currency %>
  <br>
  <br>
  <%= f.label :literacy_rate, 'Literacy Rate (%):' %>
  <%= f.number_field :literacy_rate, in: 1.0..100.0, step: 1.0 %>
  <br>
  <br>
  <%= f.label :governing_party, 'Governing Party:' %>
  <%= f.text_field :governing_party %>
  <br>
  <br>
  <%= f.submit 'Add Country!!' %>
<% end %>
</div>
</div>

app/views/cities/show.html.erb
<!-- <body STYLE="background-image: url(<%= @country.flag_image %>)"></body> -->

<div id="bg">
  <img src="<%= @country.flag_image %>" alt="">
</div>

<div class='container'>
<div class='holder'>

<h1><%= @country.name %></h1>
<%= image_tag(@country.flag_image, alt: "alt text is always required", width:200) %>
<p><b>Population: </b><%= number_to_human(@country.population) %>.</p>
<p><b>Size: </b><%= number_to_human(@country.size) %> square miles.</p>
<p><b>GDP: </b><%= number_to_human(@country.gdp, units: {unit: "Billion", thousand: "Trillion"}) %> dollars US.</p>
<p><b>Languages: </b><%= @country.language %>.</p>
<p><b>Currency: </b><%= @country.currency %>.</p>
<p><b>Literacy Rate: </b><%= @country.literacy_rate %>%</p>
<p><b>Governing Party: </b><%= @country.governing_party %></p>

<%= button_to('Delete Country', country_path(@country), method: :delete, data:{confirm: "Delete country? Are you sure?"}) %>
<%= link_to("Edit Country", edit_country_path(@country)) %>

</div>


</div>

app/views/countries/edit.html.erb
<div class='container'>
<div class='holder'>


<%= render @country %>


</div>
</div>

app/views/countries/index.html.erb
<div class='container'>
  <div class='holder'>
    <% @countries.sort.each do |country| %>
    
    <%= link_to(country.name, country_path(country)) %>
    <%#= button_to('Delete Country', country_path(country), method: :delete, data:{confirm: "Delete country? Are you sure?"}) %>
    <%#= link_to("Edit Country", edit_country_path(country)) %>
    <br>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CIAApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class='title_bar'>
<h1>THIS IS THE CIA COUNTRIES DATABASE</h1>


  
</div>

<%= yield %>


<footer class='footer'>
  
    <%= link_to('All Countries', countries_path) %>    |    <%= link_to('New Country', new_country_path) %>    |    <%= link_to('All Cities', cities_path) %>    |    <%= link_to('New City', new_city_path) %>    
  
</footer>
</body>
</html>